spring: # spring
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS

server: # 服务
  port: 8080
  servlet:
    context-path: /api${api.version}



mybatis: # Mybatis
  mapperLocations: classpath*:mapper/*.xml

api.version: 1 # api版本号