spring: # spring
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS

server: # 服务
  port: 9080
  servlet:
    context-path: /echoes${api.version}

mybatis: # Mybatis
  mapperLocations: classpath*:mapper/*.xml

api.version: 0.1 # api版本号